name:                algorithms-and-data-structures-hs
version:             0.0.0.1
github:              "JCPedroza/algorithms-and-data-structures-hs"
license:             MIT
author:              "JCPedroza"
maintainer:          "nemesis4go10@@hotmail.com"
copyright:           "2022 JCPedroza"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Algorithms and data structures implemented in Haskell.
# category:            Algorithms and data structures.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JCPedroza/algorithms-and-data-structures-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  algorithms-and-data-structures-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algorithms-and-data-structures-hs

tests:
  algorithms-and-data-structures-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algorithms-and-data-structures-hs
